### ISSUE TITLE
Project Setup: Use Cases, Milestones, Roadmap

### ISSUE THREAD

**Issue by felixboehm** [toplocs/tribelike#2]
- [x] Add Features as Github Issues
- [x] Document Uses Cases in github Wiki (better ideas?) 
- [ ] ~~Define a Tag per Use Case and add it to Feature Issues~~ 
- [x] Highlevel Roadmap
- [x] Planning
- [x] Kanban Board

Maybe there is a better way to have Use Cases documented and Features linked to them?

We should also try the github "Discussions" for Ideas, Brainstorming, Discussing and decisions in the team.

---

## Use Cases

Main - Motivation

* While traveling I want to find communities in the location I will go next.

OnBoarding and Discovery

* As a User I want to find people and activities around me based on my interests
* As a User I want to discover interests around me to develop my interests, then connect and learn upon them.

Discover local Communities, People and Activities

* Meet likeminded people in your area
* While traveling I want to find communities in the location I will go next.

My Communities

* Discover for yourself what are your interests
* Stay active in communitites which are important for you
Participate in local Communities

Connecting

Governance / Trust

* As a “Community Manager” I want to create and grow a Community. Ownership should lie with the Community contributors and more active and trusted members should be able to govern transparently.
* As a passive member of a Community I want to delegate (liquid vote) trust to contributors to support them growing the Community.
